language: python
sudo: false
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
  - "python setup.py install"
script:
  - "py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls
