language: python
sudo: false
os:
  - linux
#  - osx # Travis-CI doesn't work well with OSX + python yet
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements/base.txt"
  - if [ `python -c 'import sys; print(sys.version_info[0])'` = '3' ]; then pip install -r requirements/python3.txt; fi
  - if [ `python -c 'import sys; print(sys.version_info[0])'` = '2' ]; then pip install -r requirements/python2.txt; fi
  - "pip install -r tests/requirements.txt"
  - "python setup.py install"
script:
  - "py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls
