language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "pypy"
#  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
script:
  - "py.test tests/unit/ --cov pad --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls