language: python
sudo: false
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- pypy
- pypy3
install:
- pip install -r requirements/base.txt
- if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r requirements/python2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip install -r requirements/python3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements/pypy2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -r requirements/pypy3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install -r requirements/pypy3.txt; fi
- pip install -r requirements/tests.txt
- python setup.py install
- wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
- gunzip GeoIP.dat.gz
- wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
- gunzip GeoIPv6.dat.gz
- mdns.py --port 30053 --detach
script:
- py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing
- py.test tests/functional/
after_script:
- pep8 --show-source pad
after_success:
- coveralls
notifications:
  email:
    secure: KQxfGXb3gk23vdaf1WtbFBVhIB1yreEJH8aBn4CWFKw1DcR8Yu/plPWXSxXtOiaJpsZHbmG9Zry+Hft+qUE3LY4EreqVDcDVsn3i/fJ5Yj4D0ag/3g+t5uW9fq8fjCOQB5TPft2yKJDrV/xrUvVOw/UiY0M6rBdJIg2zuVtb3kfSAHD8IF6BVJKztwPJf+reKvP5UWKH40wJQMOTBqooiavtQFAxYJgz6DtWdm+GNE+islMshFp7uZ5sn//qVVXZr0K1Cl60A04L5L4hKAiaF5FEKBGeu+0OxIXC8hAplMRmEQeS2kbqNv18W3u6OMrUalPx/XiF4u0kVuZNnHdDlLQeqClQgYW96pkvt4Z79H856dvWzE4/faeula6PkF9vd1GrIX0AddV6xxXFUKrXgaJrLLL0bhyTkU/GVQyutv2kuzm2ueCL7CFB+3KWGz0KDFaMzXz1p+jcIGSLLFVDjgw5Nv+z0C4iqPfZDai9WM5WzNwMAQHO8kUTlMwNmJj1x5vYSEbk+rEpfph2RHXUqPlhI56hyGPiDhtqW5oc83ASVg0I6b0SOiGQzbaBet0sKA/di3/2psLwGAxRAeLMofThCt/VjgmIwPVBOZ6lPToD/ytMxFhSLM7ttt0UKO9sC3A1YG6ziItVeX/w68k7X0USQbDy5ZnDh2tc+P/u61k=
