language: python
sudo: false
os:
  - linux
#  - osx # Travis-CI doesn't work well with OSX + python yet
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements/base.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r requirements/python3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip install -r requirements/python3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements/pypy2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install -r requirements/pypy3.txt; fi
  - pip install -r requirements/tests.txt
  - python setup.py install
script:
  - "py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls
