language: python
sudo: false
os:
- linux
env:
  matrix:
    - USE_YAML=1
python:
- '3.5'
install:
- pip install -r requirements/base.txt;
- if [[ $USE_SQLALCHEMY == false ]]; then pip install pymysql; fi
- if [[ $USE_SQLALCHEMY == true ]]; then pip install sqlalchemy; fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r requirements/python2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip install -r requirements/python3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements/pypy2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -r requirements/pypy3-build-requirements.txt;pip install -r requirements/pypy3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install -r requirements/pypy3-build-requirements.txt;pip install -r requirements/pypy3.txt; fi
- pip install -r requirements/tests.txt
- python setup.py install
- wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
- gunzip GeoIP.dat.gz
- wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
- gunzip GeoIPv6.dat.gz
before_script:
- if [[ $USE_SQLALCHEMY == false ]]; then mysql -u root -e 'create database spampad;'; fi
script:
- env USE_PICKLES=0 py.test tests/functional/test_plugins/test_dkim.py::TestFunctionalDKIM::test_def_whitelist_from_address
- cat tests/test_match_conf/*
