language: python
sudo: false
os:
- linux
env:
  matrix:
#    - USE_SQLALCHEMY=true
#    - USE_SQLALCHEMY=false
    - USE_YAML=1
python:
#- '2.7.11'
#- '3.5'
- pypy
#- pypy3
install:
- pip install -r requirements/base.txt;
- if [[ $USE_SQLALCHEMY == false ]]; then pip install pymysql; fi
- if [[ $USE_SQLALCHEMY == true ]]; then pip install sqlalchemy; fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install -r requirements/python2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then pip install -r requirements/python3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements/pypy2.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -r requirements/pypy3-build-requirements.txt;pip install -r requirements/pypy3.txt; fi
- if [[ $TRAVIS_PYTHON_VERSION == pypy3 ]]; then pip install -r requirements/pypy3-build-requirements.txt;pip install -r requirements/pypy3.txt; fi
- pip install -r requirements/tests.txt
- python setup.py install
- wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
- gunzip GeoIP.dat.gz
- wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
- gunzip GeoIPv6.dat.gz
before_script:
- if [[ $USE_SQLALCHEMY == false ]]; then mysql -u root -e 'create database spampad;'; fi
script:
#- py.test tests/unit/ --cov pad --cov scripts --cov-report term-missing
#- env USE_PICKLES=0 py.test tests/functional/ -vv
#- if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then env USE_PICKLES=1 py.test tests/functional/ -vv ; fi
#- py.test tests/profiling/
 - env USE_PICKLES=1 py.test tests/functional/test_received_parser.py::TestReceivedParser::test_header_msg_ignore_localhost
#after_script:
#- cat .profile_results/*report.txt
#- pep8 --show-source pad
#after_success:
#- bash <(curl -s https://codecov.io/bash)
#- coveralls